### PR TITLE
deleting troubleshooting.md document

### PR DESCRIPTION
**Pull request by hubvu**
- Deleting > https://docs.ondat.io/docs/operations/troubleshooting/ which has now been transferred to the https://docs.ondat.io/docs/knowledgebase/ section.
  - Redirects from https://docs.ondat.io/docs/operations/troubleshooting/ to https://docs.ondat.io/docs/knowledgebase/ should be setup.

### CODE REVIEW

**Review by cannischan — APPROVED** [review]
lgtm

**Comment by cannischan** [comment]
@Arau merged now - thanks !

**Comment by Arau** [comment]
Redirect validated

```
Connecting to docs.ondat.io (docs.ondat.io)|104.26.11.114|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 301 Moved Permanently
  Date: Wed, 21 Sep 2022 12:43:11 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: max-age=3600
  Expires: Wed, 21 Sep 2022 13:43:11 GMT
  Location: https://docs.ondat.io/docs/knowledgebase/
  Report-To: {"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=yvm8TF9S2NvtSu%2B8B1vvnjNKUMdV7y6hnGxxoqkUUCV2%2BLXkziFX8R%2F0R6gIwNmkYKAiIzhBZ8lSIA%2FowoEYwjOqlxv%2BDTblNPTp5P2BX02aaFA4uvJQXkXoG80v2Pw%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Vary: Accept-Encoding
  Server: cloudflare
  CF-RAY: 74e2e297c9f6d184-LHR
Location: https://docs.ondat.io/docs/knowledgebase/ [following]
--2022-09-21 13:43:11--  https://docs.ondat.io/docs/knowledgebase/
Reusing existing connection to docs.ondat.io:443.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Wed, 21 Sep 2022 12:43:12 GMT
  Content-Type: text/html; charset=utf-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  Last-Modified: Wed, 21 Sep 2022 11:14:13 GMT
  Access-Control-Allow-Origin: *
  expires: Wed, 21 Sep 2022 11:35:04 GMT
  Cache-Control: max-age=600
  x-proxy-cache: MISS
  X-GitHub-Request-Id: 080B:CA91:99D6CE:9EC841:632AF490
  Via: 1.1 varnish
  Age: 11
  X-Served-By: cache-lcy19264-LCY
  X-Cache: HIT
```

**Comment by hubvu** [comment]
> Redirect validated
> 
> ```
> Connecting to docs.ondat.io (docs.ondat.io)|104.26.11.114|:443... connected.
> HTTP request sent, awaiting response...
>   HTTP/1.1 301 Moved Permanently
>   Date: Wed, 21 Sep 2022 12:43:11 GMT
>   Transfer-Encoding: chunked
>   Connection: keep-alive
>   Cache-Control: max-age=3600
>   Expires: Wed, 21 Sep 2022 13:43:11 GMT
>   Location: https://docs.ondat.io/docs/knowledgebase/
>   Report-To: {"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=yvm8TF9S2NvtSu%2B8B1vvnjNKUMdV7y6hnGxxoqkUUCV2%2BLXkziFX8R%2F0R6gIwNmkYKAiIzhBZ8lSIA%2FowoEYwjOqlxv%2BDTblNPTp5P2BX02aaFA4uvJQXkXoG80v2Pw%3D"}],"group":"cf-nel","max_age":604800}
>   NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
>   Vary: Accept-Encoding
>   Server: cloudflare
>   CF-RAY: 74e2e297c9f6d184-LHR
> Location: https://docs.ondat.io/docs/knowledgebase/ [following]
> --2022-09-21 13:43:11--  https://docs.ondat.io/docs/knowledgebase/
> Reusing existing connection to docs.ondat.io:443.
> HTTP request sent, awaiting response...
>   HTTP/1.1 200 OK
>   Date: Wed, 21 Sep 2022 12:43:12 GMT
>   Content-Type: text/html; charset=utf-8
>   Transfer-Encoding: chunked
>   Connection: keep-alive
>   Last-Modified: Wed, 21 Sep 2022 11:14:13 GMT
>   Access-Control-Allow-Origin: *
>   expires: Wed, 21 Sep 2022 11:35:04 GMT
>   Cache-Control: max-age=600
>   x-proxy-cache: MISS
>   X-GitHub-Request-Id: 080B:CA91:99D6CE:9EC841:632AF490
>   Via: 1.1 varnish
>   Age: 11
>   X-Served-By: cache-lcy19264-LCY
>   X-Cache: HIT
> ```

Thanks!

**Pull request merged**
